In [1]:
#numpy
!pip install numpy --trusted-host pypi.org --trusted-host files.pythonhosted.org


You should consider upgrading via the 'c:\users\312350\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [ ]:
array_one = np.array([0,1,3,5,7,9])

In [3]:
 num = [11,22,33,44,55,66,77]
array2 = np.array(num)
array2

array([11, 22, 33, 44, 55, 66, 77])

In [5]:
array_of_zeroes =np.zeros((2,3))
array_of_zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#dtype si data type
array_of_ones = np.ones((2,3),dtype=np.int32)
array_of_ones

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
#diagonal will be 1 rest would be 0
array_eye  = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
#creates array with lower bound, upper bound and interval
array_of_even = np.arange(2,24,2)
array_of_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [11]:
#2d arrays
array_2d = np.array([(3,4,6),(7,8,9)])
array_2d

array([[3, 4, 6],
       [7, 8, 9]])

In [13]:
array_2d.shape

(2, 3)

In [15]:
#creates an array of 8 elements staring from 0 with interval 1
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
array_nd = np.arange(8).reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
x  = np.arange(8)

In [19]:
print(x)

[0 1 2 3 4 5 6 7]


In [20]:
y = np.arange(8).reshape(2,4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
z = np.arange(36).reshape(3,4,3)
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [24]:
p = np.array([1,2,4])
q=np.array([3,4,5])
print(p+q)
print(p-q)
print(p%q)

[4 6 9]
[-2 -2 -1]
[1 2 4]


In [27]:
milege = np.arange(45,55,2)
milege

array([45, 47, 49, 51, 53])

In [29]:
milege.sum()


245

In [30]:
milege.max()

53

In [32]:
milege.mean()

49.0

In [33]:
num = np.arange(16).reshape(4,4)
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
#inidividual column sum 
num.sum(axis=0)

array([24, 28, 32, 36])

In [36]:
#inidividual row sum ->
num.sum(axis =1 )

array([ 6, 22, 38, 54])

In [38]:
np.median(milege)

49.0

In [39]:
#indexing and slicing
x =np.arange(10)**3
x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [40]:
#accesing
x[3]

27

In [41]:
#accesing using -
x[-4]

216

In [42]:
x[1:8]

array([  1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [43]:
x[3:-3]

array([ 27,  64, 125, 216], dtype=int32)

In [44]:
companies = np.array([['Samsung','Microsoft','IBM','Spotify','Flipkart'],
                     [1938, 1975, 1911, 2006, 2007],
                     [489000, 131000, 380000, 3000, 30000]])

In [45]:
companies[:,2]

array(['IBM', '1911', '380000'], dtype='<U11')

In [47]:
companies[0,2]

'IBM'

In [48]:
#subset of range or column ,row indices followed by column indices
companies[0:2,2:4]

array([['IBM', 'Spotify'],
       ['1911', '2006']], dtype='<U11')

In [49]:
companies[:,2:4]

array([['IBM', 'Spotify'],
       ['1911', '2006'],
       ['380000', '3000']], dtype='<U11')

In [51]:
#iterating through arrays
for i in x:
    print(i)

0
1
8
27
64
125
216
343
512
729


In [53]:
for row in companies:
    print(row)

['Samsung' 'Microsoft' 'IBM' 'Spotify' 'Flipkart']
['1938' '1975' '1911' '2006' '2007']
['489000' '131000' '380000' '3000' '30000']


In [55]:
companies.flatten()

array(['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart', '1938',
       '1975', '1911', '2006', '2007', '489000', '131000', '380000',
       '3000', '30000'], dtype='<U11')

In [61]:
#flatttened column wise
for data in companies.flatten(order = 'F'):
    print(data)

Samsung
1938
489000
Microsoft
1975
131000
IBM
1911
380000
Spotify
2006
3000
Flipkart
2007
30000


In [62]:
#changing shape of an array
tech_companies = np.array([('IBM', 'Apple Inc.', 'Intel', 'Dell', 'Microsoft'),
                           ('New York', 'California', 'California', 'Texas', 'Washington')])

tech_companies


array([['IBM', 'Apple Inc.', 'Intel', 'Dell', 'Microsoft'],
       ['New York', 'California', 'California', 'Texas', 'Washington']],
      dtype='<U10')

In [64]:
tech_companies.shape

(2, 5)

In [65]:
#transpose
tech_companies.T

array([['IBM', 'New York'],
       ['Apple Inc.', 'California'],
       ['Intel', 'California'],
       ['Dell', 'Texas'],
       ['Microsoft', 'Washington']], dtype='<U10')

In [66]:
tech_companies.reshape(5,2)

array([['IBM', 'Apple Inc.'],
       ['Intel', 'Dell'],
       ['Microsoft', 'New York'],
       ['California', 'California'],
       ['Texas', 'Washington']], dtype='<U10')

In [68]:
#let the (ie in case -1)compiler decide what values is to be passed for rows 
companies.reshape(-1,5)

array([['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'],
       ['1938', '1975', '1911', '2006', '2007'],
       ['489000', '131000', '380000', '3000', '30000']], dtype='<U11')

In [70]:
#creating one array x same as that o y which has only 
x = np.ones_like(y)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#last 20 rows and columns 2-5 of an array
array = array-orig[-20:2-6]




In [73]:
y=np.arange(2,4,0.5)
y

array([2. , 2.5, 3. , 3.5])

In [74]:
x=np.array([4,6,2,8])
np.median(x)

5.0